### ISSUE TITLE
Privacy enhancement/feature request, Allowing choco API access from Tor Exit nodes

### ISSUE THREAD

**Issue by AnonymousPlanet** [chocolatey/home#14]
Hello,

I would like to kindly submit this enhancement/feature request for consideration.

Currently Choco will install fine fine on Windows (through Tor) without issues. However installing/upgrading any package will fail as shown in the following error:

    C:\Windows\system32>choco install git
    Chocolatey v0.10.15
    Installing the following packages:
    git
    By installing you accept licenses for the packages.
    Error retrieving packages from source 'https://chocolatey.org/api/v2/':
     The remote server returned an error: (403) Forbidden.
    git not installed. The package was not found with the source(s) listed.
     Source(s): 'https://chocolatey.org/api/v2/'
     NOTE: When you specify explicit sources, it overrides default sources.
    If the package version is a prerelease and you didn't specify `--pre`,
     the package may not be found.
    Please see https://chocolatey.org/docs/troubleshooting for more
     assistance.This issue is consistent with all Tor Exit nodes.Steps to reproduce: 

* install Choco on any Windows Running VM with all traffic routed through the Tor Onion network (using Whonix Gateway or pfSense for instance). 
* try any package install using choco install 

Expected result: 

Should work 

Actual result (from log): 

[WARN ] - Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 The remote server returned an error: (403) Forbidden.

Troubleshooting steps:

Checking with browser indicates that access is protected by Cloudflare and is possible but requires hCaptcha solving when using a Tor Exit node. This is however not possible with the command line client. 

This could be solved by changing a simple firewall rule or setting in Cloudflare dashboard to allow Tor Exit nodes on the API. This issue does not affect VPN users. 

Choco would also be very useful and convenient to many users who want a bit more privacy by using the Tor onion network. 

Thank you in advance for maybe considering this request.

AnonymousPlanet

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1057) by [Unito](https://www.unito.io)

**Comment by ferventcoder** [comment]
Moving this over to chocolatey/home. That will allow us to hook it up to the internal issue.

**Comment by AnonyPla** [comment]
Would it be possible to kindly ask an update on this request? 

As of today, the API access is still closed to Tor Exit nodes bringing a 503 error.

I still think this issue could be resolved with just a couple clicks in the Cloudflare administration panels. This would really help a lot of Tor users.

**Comment by Windos** [comment]
Hi @AnonyPla, we currently have Cloudflare's [Onion Routing](https://blog.cloudflare.com/cloudflare-onion-service/) service enabled though my understanding is this only really helps when browsing using certain browsers.

In looking into traffic patterns, about 1/3 of all traffic from the Tor network is currently being challenged while the remainder is being allowed through without issue. A large percentage of the unchallenged traffic has the Chocolatey user agent attached. This indicates to me that the decision to challenge or not is based on the security score of individual exit nodes, rather than it being a blanket action taken against all Tor traffic or specificially non-browser traffic.

Unfortuantly, we're unable to override this behaviour with a Firewall Rule (e.g. bypassing or allowing all traffic from the "Tor" pseudo country) as Cloudflare's traffic sequence means that this would result in traffic from the Tor network sidestepping the [rate limit](https://docs.chocolatey.org/en-us/community-repository/community-packages-disclaimer#rate-limiting).

It is a pain, I know. The work around atm to preserve anonymity would be to access the [community repo](https://community.chocolatey.org/packages/) via a browser, download desired packages, then install them from the .nupkg file on your local disk. Unfortunatly, this will be _very_ tedious for packages with long dependency chains.

This also only helps with the Chocolatey website side of things, packages will still reachout to the web to download installers so if _those_ websites don't trust traffic from the Tor network the install will fail.

**Comment by AnonyPla** [comment]
Okay then ... May I suggest another proposal? On your main webserver with the API denying tor access ... 

- Install Tor
- Set up a hidden service pointing to the API using an Nginx reverse proxy (easy enough to do)
- Add an option to choco like --tor so that that choco will use the Tor hidden service API for updates instead and then it would allow choco to at least contact the API ... It won't resolve any repository blocking tor nodes but at least the choco API would be available to Tor users ... You can set up rate limiting and various other methods to prevent abuse on the hidden service.

**Comment by AnonyPla** [comment]
This could be done on a very small 2-3$ VPS / month entirely isolated from your other servers ... easy to cut off in case of abuse... It's just the API after all ... And you know what? I'm willing to offer you the cheap VPS in question for year if you're willing to try this ...

**Comment by AnonyPla** [comment]
https://github.com/allow-tor/on-cloudflare works too

**Comment by Windos** [comment]
The trouble with what's laid out in [allow-tor/on-cloudflare](https://github.com/allow-tor/on-cloudflare), and to an extent the VPS route, is that it results in the traffic bypassing our other firewall rules, rate limiting, and the [Cloudflare managed rules](https://developers.cloudflare.com/waf/managed-rulesets).

Also, we'd be very hesitant to not have Cloudflare sit in front of any new endpoints (again, we'd be missing a lot of security features afforded by Cloudflare), and so we end up back in the same position we began in.

Unfortunately, at this point we won't be taking this issue forward and I'll be closing it.

Individuals can work around this by visiting the [community repo](https://community.chocolatey.org/packages/) via a browser (enabled using Cloudflare's [Onion Routing service](https://blog.cloudflare.com/cloudflare-onion-service/)), downloading desired packages, then installing them from the .nupkg file on their local disk.

Alternatively, one could consider setting up their own [proxy repository](https://docs.chocolatey.org/en-us/features/host-packages)/general proxy (on a VPS) that has its upstream set to the Chocolatey Community Repository over the internet and a hidden service on it that allows the owner to connect to it via the Tor network. Note that this is untested, and naturally the owner would be responsible for the security and maintenance of it.

**Comment by ferventcoder** [comment]
> Alternatively, one could consider setting up their own [proxy repository](https://docs.chocolatey.org/en-us/features/host-packages)/general proxy (on a VPS) that has its upstream set to the Chocolatey Community Repository over the internet and a hidden service on it that allows the owner to connect to it via the Tor network. Note that this is untested, and naturally the owner would be responsible for the security and maintenance of it.

Highlighting this a bit more as I think this is a really good best of both worlds. You wouldn't have to do much more than setting up a Nexus Repository somewhere and you'd have it all good to go within 10-20 minutes (which includes installing it).
