### ISSUE TITLE
I find it difficult to find the login page for my account on Chocolatey Community Repository

### ISSUE THREAD

**Issue by michaelklishin** [chocolatey/home#238]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

I maintain an open source package and find it really difficult to find the maintainer login/account page. Every single time I have to google "chocolatey login" to get to https://community.chocolatey.org/users/account/LogOn, or use a bookmark.

Please make it dead obvious how to log on the Community page. It can be just me but somehow
I don't have this problem on GitHub, NPM, RubyGems, Clojars, crates.io, and other similar resources.

### What is Expected?

It is really really easy for maintainers to find a login page for their account. At least after you follow the Community link.

### How Did You Get This To Happen?

1. Navigate to chocolatey.org
2. Try to find your account or login link without using Google.

### System Details

All of this is irrelevant, this is a UI issue.

### Installed Packages

```bash
Not relevant.
```

### Output Log

```bash
Not relevant.
```

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1202) by [Unito](https://www.unito.io)

**Comment by pauby** [comment]
> Every single time I have to google "chocolatey login" to get to https://community.chocolatey.org/users/account/LogOn, or use a bookmark.

The login button is at community.chocolatey.org/packages (which is the Chocolatey Community Repository). From there, click the Login button.

![image](https://user-images.githubusercontent.com/12760779/209157010-24f28a5f-20ca-4370-bcd7-ea0a6104499a.png)

The login button may be covered by search help. Click anywhere on the page to make that go away.

> Navigate to chocolatey.org

The Chocolatey Community Repository is at https://community.chocolatey.org/packages. The Chocolatey Community website is at https://community.chocolatey.org. If you are looking for Chocolatey For Business and other licensed / commercial information, then use https://chocolatey.org.

**Comment by michaelklishin** [comment]
So you are saying that maintainers are supposed to know that the main site is a shopping window for Chocolatey Business and they have to use a subdomain. Fair enough.

But then at least make the login link right there on the Community section home page?

I don't really care where it is, if people have to google your login page you clearly have a UX issue. Please relabel this as a bug because it is.

**Comment by pauby** [comment]
> So you are saying that maintainers are supposed to know that the main site is a shopping window for Chocolatey Business and they have to use a subdomain. Fair enough.

Okay, let's just address tone first of all. You're coming across aggressive and angry. I get you're having difficulty finding the login link. But this isn't helping me wanting, to help you. And lets put it into context. It's a login link.

[Chocolatey.org](https://chocolatey.org) and [Chocolatey Community Repository](https://community.chocolatey.org) have been separate sites since March 31st 2021. If you are visiting chocolatey.org, then you're visiting the wrong site. 

Chocolatey.org has this as it's title page:

![image](https://user-images.githubusercontent.com/12760779/209169872-46766272-0f19-469a-8406-7ff074ce4e93.png)

There is the main title and then there is the Community link.

The Chocolatey Community Repository has this on the homepage:

![image](https://user-images.githubusercontent.com/12760779/209170052-8acf6bd7-d5c9-4a24-ad7f-f4dee9308224.png)

> But then at least make the login link right there on the Community section home page?

You've got a point. We perhaps should do that. And if your issue said just that, we'd probably agree right now.

> I don't really care where it is, if people have to google your login page you clearly have a massive UX issue. Please relabel this as a bug because it is.

Nobody has ever said they are Googling for the login page. You're the first. This isn't a massive UX issue. This is a massive UX issue _for you_. And I understand that. I don't say it to be flippant. I say it for context.

Please [bookmark the login page](https://community.chocolatey.org/users/account/LogOn), and you can jump right to it or follow the steps I provided: https://community.chocolatey.org/packages -> Click `Login`.

> Please relabel this as a bug because it is.

This isn't a bug. It's an enhancement if we decide to add it.

**Comment by michaelklishin** [comment]
Seriously, people have to google your login page and the solution is to tell them to bookmark it? 🤦‍♂️ 

I cannot name a single package hosting service that has this problem. No need to triage anything, I give up.

**Comment by michaelklishin** [comment]
I wonder if you would tell the same thing to customers who cannot find a link to whatever form they use to buy or request a quote for your product. Tells a lot about company priorities I guess.

**Comment by michaelklishin** [comment]
Just to see if I am right that every other package hosting services I have used does not have this problem, I have gone to check out

 * crates.io: login link right in the header
 * clojars.org: login link right in the header
 * PyPI: login link right in the header
 * rubygems.org: login link right in the header
 * npmjs.org: login link right in the header
 * oss.sonatype.org: login link right in the header
 * packagist.org: : login link right in the header

To contrast:

 * chocolatey.org: you have to google the link, bookmark it or know where exactly it is on the site, or guess that you have to click "Find packages", find your package and then see the login button

So there is clear a systematic difference between Chocolatey and seven other services that — this is highly unscientific — appears to be really important and relevant.

But sure, it's just me and I come around not super nice so let's ignore the fact above!

**Comment by pauby** [comment]
I've reopened the issue as it is still in triage and something for us to consider but I have also locked it.

These types of responses are not something we want to see in the community, and they are not conducive to being a good community member. If you raise any issues in future, please follow the [Code Of Conduct](https://github.com/chocolatey/.github/blob/main/CODE_OF_CONDUCT.md) when doing so.
