### ISSUE TITLE
Manually moved package installed by Chocolatey can never be searched by Windows system

### ISSUE THREAD

**Issue by cbtang01** [chocolatey/home#73]
I Installed mingw package with Chocolatey in my Windows pc.  Chocolatey automatically placed Mingw at C:\ProgramData\chocolatey\lib\mingw\tools\install\Mingw\... without asking me for a user-selected location.  So I manually move mingw to another desired location and set the environment path to that other location.  Now, every time I try to execute any *.exe in mingw\bin\*.exe in command prompt, the system always says "Cannot find file at '..\\lib\mingw\tools\install\mingw64\bin\gcc.exe' (c:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe).This usually indicates a missing or moved file."  

It never searches the executable in the environment path I set.

I tried "cuninst" with all kinds of options (e.g. -n, etc.), the system still gave me the same message.
 
How do I fix this?

**Comment by pauby** [comment]
This is the default location where Chocolatey packages will be placed (under the lib folder of the [location Chocolatey is installed to](https://docs.chocolatey.org/en-us/faqs#where-does-chocolatey-install-by-default) (`c:\programdata\chocolatey` by default). Chocolatey won't ask you for a location to install the packages to.

Chocolatey has shimmed the executables so that they are accessible on the path and moving them will break this link. When you moved them, the shims still point to the old location.

The solution is to move them back to where they were.

See these [docs](https://docs.chocolatey.org/en-us/faqs#can-i-override-the-installation-directory) around overriding the install location.

**Comment by cbtang01** [comment]
Thanks Paul.  I re-installed the package and uninstall it using cunst.  The shims are now gone.  As for the --dir option to override the default installation location, I am not a customer of Chocolatey to be allowed to use option.  So, I simply go to SourceForge, download my package zip and unzip to my desired location.
